### PR TITLE
Add True Positive

### PR DESCRIPTION
**Pull request by veeral-patel**
Hi! Adding a tool for case management I've been working on that I believe the users of this repo will find useful.

### CODE REVIEW

**Comment by veeral-patel** [comment]
@meitar Hey - have you gotten the chance to look at this PR? It's a 1 line change and it won't take more than 10 seconds to review!

**Comment by meitar** [comment]
@veeral-patel:

> have you gotten the chance to look at this PR?

Not yet, sorry. I know it's a small change but I'd like a chance to actually look at True Positive more closely before I merge, only because I've never heard of it before.

**Comment by veeral-patel** [comment]
@meitar Hi Meitar -- no worries. Didn't mean to rush you, just wanted to convey how small of a change my PR is.

Can I provision an account for you in the tool so you can try it for yourself? What's your email address or Twitter handle?

**Comment by meitar** [comment]
> Didn't mean to rush you, just wanted to convey how small of a change my PR is.

I understand. Almost all PRs for this repo are this small, though. :)

> Can I provision an account for you in the tool so you can try it for yourself? What's your email address or Twitter handle?

Thank you, but no thanks. I'll sign up for the "starter" account to have a look when I get a chance. Thanks for your patience.

FWIW, I'm only holding off because I can't easily find ready references of other reputable users of this tool *and* I personally am not familiar with it, so it seems like it's still not a mature tool. That's not an inherent disqualifier in my book but I do like to attempt some due diligence for this list.

**Comment by veeral-patel** [comment]
@meitar Got it. So for it to be added you need references to other users of this tool and for you to try it out?

**Comment by meitar** [comment]
> So for it to be added you need references to other users of this tool and for you to try it out?

It is not a hard and fast rule but in general I prefer to add tools only after I can at least cursorily verify some significant awareness of them in the cybersecurity industry.m so that this list remains a reference guide and not an advertising venue.

**Comment by veeral-patel** [comment]
@meitar Got it, I totally understand, thanks for letting me know.

**Pull request closed without merging**
